default:
  image: node:lts
  cache:
    paths:
      - node_modules/
  before_script:
    - pnpm install
    - echo \"$CI_PIPELINE_IID\" > public/build.json

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run lint

deploy:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN
