default:
  image: node:lts
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
    - echo \"$CI_PIPELINE_IID\" > src/static/build.json

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public/

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN
