// Timer
export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIME = 'RESET_TIME';
export const START_INSPECTION = 'START_INSPECTION';

// Activation
export const PREPARE_ACTIVATION = 'PREPARE_ACTIVATION';
export const RESET_ACTIVATION = 'RESET_ACTIVATION';
export const INCREMENT_PREPARATION_STAGE = 'INCREMENT_PREPARATION_STAGE';
export const SKIP_PREPARATION_STAGE = 'SKIP_PREPARATION_STAGE';
export const PREPARE_INSPECTION = 'PREPARE_INSPECTION';
export const FAIL_INSPECTION = 'FAIL_INSPECTION';

// Times
export const SET_SCRAMBLE = 'SET_SCRAMBLE';
export const REFRESH_SCRAMBLE = 'REFRESH_SCRAMBLE';
export const SAVE_TIME = 'SAVE_TIME';
export const REMOVE_TIME = 'REMOVE_TIME';
export const UPDATE_TIME = 'UPDATE_TIME';
export const CLEAR_TIMES = 'CLEAR_TIMES';

// Archive
export const LOAD_TIMES = 'LOAD_TIMES';
export const INPUT_ARCHIVE_TITLE = 'INPUT_ARCHIVE_TITLE';
export const ARCHIVE_CURRENT_TIMES = 'ARCHIVE_CURRENT_TIMES';
export const ARCHIVE = 'ARCHIVE';
export const EXPAND_ARCHIVE_ITEM = 'EXPAND_ARCHIVE_ITEM';
export const COLLAPSE_ARCHIVE_ITEM = 'COLLAPSE_ARCHIVE_ITEM';
export const REMOVE_ARCHIVE_ITEM = 'REMOVE_ARCHIVE_ITEM';
export const SORT_ARCHIVE = 'SORT_ARCHIVE';
export const FILTER_ARCHIVE = 'FILTER_ARCHIVE';

// Settings
export const CHANGE_ACTIVATION_DURATION = 'CHANGE_ACTIVATION_DURATION';
export const CHANGE_PUZZLE = 'CHANGE_PUZZLE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const TOGGLE_INSPECTION_TIME = 'TOGGLE_INSPECTION_TIME';

// Modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
