// Timer
export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const RESET_TIME = "RESET_TIME";
export const START_INSPECTION = "START_INSPECTION";
export const SUBMIT_TIME_INPUT = "SUBMIT_TIME_INPUT";
export const UPDATE_TIME_INPUT = "UPDATE_TIME_INPUT";
export const SET_IS_TRAINING = "SET_IS_TRAINING";

// Activation
export const PREPARE_ACTIVATION = "PREPARE_ACTIVATION";
export const RESET_ACTIVATION = "RESET_ACTIVATION";
export const INCREMENT_PREPARATION_STAGE = "INCREMENT_PREPARATION_STAGE";
export const SKIP_PREPARATION_STAGE = "SKIP_PREPARATION_STAGE";
export const PREPARE_INSPECTION = "PREPARE_INSPECTION";
export const FAIL_INSPECTION = "FAIL_INSPECTION";
