export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';

export const INCREMENT_TIME = 'INCREMENT_TIME';
export const RESET_TIME = 'RESET_TIME';

export const PREPARE_ACTIVATION = 'PREPARE_ACTIVATION';
export const FIRE_ACTIVATION = 'FIRE_ACTIVATION';

export const SET_SCRAMBLE = 'SET_SCRAMBLE';

export const SAVE_TIME = 'SAVE_TIME';
export const REMOVE_TIME = 'REMOVE_TIME';
export const CLEAR_TIMES = 'CLEAR_TIMES';
export const SHOW_TIME_DETAILS = 'OPEN_TIME_DETAILS';
export const HIDE_TIME_DETAILS = 'HIDE_TIME_DETAILS';

export const LOAD_TIMES = 'LOAD_TIMES';
export const INPUT_ARCHIVE_TITLE = 'INPUT_ARCHIVE_TITLE';
export const OPEN_ARCHIVE_MODAL = 'OPEN_ARCHIVE_MODAL';
export const CLOSE_ARCHIVE_MODAL = 'CLOSE_ARCHIVE_MODAL';
export const ARCHIVE_CURRENT_TIMES = 'ARCHIVE_CURRENT_TIMES';
export const ARCHIVE = 'ARCHIVE';
export const EXPAND_ARCHIVE_ITEM = 'EXPAND_ARCHIVE_ITEM';
export const COLLAPSE_ARCHIVE_ITEM = 'COLLAPSE_ARCHIVE_ITEM';
export const REMOVE_ARCHIVE_ITEM = 'REMOVE_ARCHIVE_ITEM';

export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const CHANGE_PUZZLE = ' CHANGE_PUZZLE';
