// Timer
export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIME = 'RESET_TIME';
export const START_INSPECTION = 'START_INSPECTION';
export const SUBMIT_TIME_INPUT = 'SUBMIT_TIME_INPUT';
export const UPDATE_TIME_INPUT = 'UPDATE_TIME_INPUT';

// Activation
export const PREPARE_ACTIVATION = 'PREPARE_ACTIVATION';
export const RESET_ACTIVATION = 'RESET_ACTIVATION';
export const INCREMENT_PREPARATION_STAGE = 'INCREMENT_PREPARATION_STAGE';
export const SKIP_PREPARATION_STAGE = 'SKIP_PREPARATION_STAGE';
export const PREPARE_INSPECTION = 'PREPARE_INSPECTION';
export const FAIL_INSPECTION = 'FAIL_INSPECTION';

// No sleep
export const NO_SLEEP_ENABLED = 'NO_SLEEP_ENABLED';
export const NO_SLEEP_DISABLED = 'NO_SLEEP_DISABLED';

// Scramble
export const SET_SCRAMBLE = 'SET_SCRAMBLE';
export const REFRESH_SCRAMBLE = 'REFRESH_SCRAMBLE';
export const SCRAMBLE_REQUESTED = 'SCRAMBLE_REQUESTED';

// Times
export const SAVE_TIME = 'SAVE_TIME';
export const REMOVE_TIME = 'REMOVE_TIME';
export const UPDATE_TIME = 'UPDATE_TIME';
export const CLEAR_TIMES = 'CLEAR_TIMES';
export const LOAD_TIMES = 'LOAD_TIMES';
export const LOAD_LOCAL_TIMES = 'LOAD_LOCAL_TIMES';
export const ARCHIVE_TIMES = 'ARCHIVE_TIMES';
export const STORED_LOCAL_TIMES = 'STORED_LOCAL_TIMES';
export const STORED_TIME = 'STORED_TIME';
export const STORED_TIMES = 'STORED_TIMES';
export const REMOVED_TIME = 'REMOVED_TIME';
export const ARCHIVED_TIMES = 'ARCHIVED_TIMES';
export const CLEARED_TIMES = 'CLEARED_TIMES';

// Authentication
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Settings
export const TOGGLE_MANUAL_TIME_ENTRY = 'TOGGLE_MANUAL_TIME_ENTRY';
export const SETTINGS_STORED = 'SETTINGS_STORED';
export const CHANGE_ACTIVATION_DURATION = 'CHANGE_ACTIVATION_DURATION';
export const CHANGE_PUZZLE = 'CHANGE_PUZZLE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const TOGGLE_INSPECTION_TIME = 'TOGGLE_INSPECTION_TIME';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
